// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pcap} from '../models';
import {models} from '../models';

export function BatchDeleteFiles(arg1:Array<number>):Promise<void>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckPermission(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DeleteFile(arg1:number):Promise<void>;

export function FollowStream(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAllFrames(arg1:string,arg2:string):Promise<string>;

export function GetCurrentUser(arg1:string):Promise<Record<string, any>>;

export function GetFileList(arg1:pcap.FileQueryReq):Promise<pcap.FileQueryResp>;

export function GetInterfaces():Promise<string>;

export function GetPacketDetail(arg1:string,arg2:number):Promise<string>;

export function GetPacketHex(arg1:string,arg2:number):Promise<string>;

export function GetPacketsByPage(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function GetWiresharkVersion():Promise<string>;

export function ImportFromPaths(arg1:Array<string>):Promise<Array<models.PcapFile>>;

export function ImportPcapsDialog():Promise<Array<models.PcapFile>>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ValidateToken(arg1:string):Promise<Record<string, any>>;
