// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePCAP(arg1) {
  return window['go']['main']['App']['AnalyzePCAP'](arg1);
}

export function BatchDeleteFiles(arg1) {
  return window['go']['main']['App']['BatchDeleteFiles'](arg1);
}

export function BatchUpdateUserStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchUpdateUserStatus'](arg1, arg2, arg3);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function CheckPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckPermission'](arg1, arg2, arg3);
}

export function CheckZeekHealth() {
  return window['go']['main']['App']['CheckZeekHealth']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteUser(arg1, arg2) {
  return window['go']['main']['App']['DeleteUser'](arg1, arg2);
}

export function FollowStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['FollowStream'](arg1, arg2, arg3);
}

export function GetAllFrames(arg1, arg2) {
  return window['go']['main']['App']['GetAllFrames'](arg1, arg2);
}

export function GetAllRoles() {
  return window['go']['main']['App']['GetAllRoles']();
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetCurrentUser(arg1) {
  return window['go']['main']['App']['GetCurrentUser'](arg1);
}

export function GetFileList(arg1) {
  return window['go']['main']['App']['GetFileList'](arg1);
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetPacketDetail(arg1, arg2) {
  return window['go']['main']['App']['GetPacketDetail'](arg1, arg2);
}

export function GetPacketHex(arg1, arg2) {
  return window['go']['main']['App']['GetPacketHex'](arg1, arg2);
}

export function GetPacketsByPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPacketsByPage'](arg1, arg2, arg3, arg4);
}

export function GetPublicKey() {
  return window['go']['main']['App']['GetPublicKey']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetWiresharkVersion() {
  return window['go']['main']['App']['GetWiresharkVersion']();
}

export function GetZeekVersion() {
  return window['go']['main']['App']['GetZeekVersion']();
}

export function GetZeekVersions() {
  return window['go']['main']['App']['GetZeekVersions']();
}

export function ImportFromPaths(arg1) {
  return window['go']['main']['App']['ImportFromPaths'](arg1);
}

export function ImportPcapsDialog() {
  return window['go']['main']['App']['ImportPcapsDialog']();
}

export function IsZeekEnabled() {
  return window['go']['main']['App']['IsZeekEnabled']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function UpdateUserProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateUserProfile'](arg1, arg2, arg3);
}

export function UpdateUserRole(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserRole'](arg1, arg2);
}

export function UpdateUserStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateUserStatus'](arg1, arg2, arg3);
}

export function ValidateToken(arg1) {
  return window['go']['main']['App']['ValidateToken'](arg1);
}
