// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDeleteFiles(arg1) {
  return window['go']['main']['App']['BatchDeleteFiles'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetAllFrames(arg1) {
  return window['go']['main']['App']['GetAllFrames'](arg1);
}

export function GetFileList(arg1) {
  return window['go']['main']['App']['GetFileList'](arg1);
}

export function GetPacketDetail(arg1, arg2) {
  return window['go']['main']['App']['GetPacketDetail'](arg1, arg2);
}

export function GetPacketHex(arg1, arg2) {
  return window['go']['main']['App']['GetPacketHex'](arg1, arg2);
}

export function GetPacketsByPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPacketsByPage'](arg1, arg2, arg3);
}

export function GetWiresharkVersion() {
  return window['go']['main']['App']['GetWiresharkVersion']();
}

export function ImportFromPaths(arg1) {
  return window['go']['main']['App']['ImportFromPaths'](arg1);
}

export function ImportPcapsDialog() {
  return window['go']['main']['App']['ImportPcapsDialog']();
}
