// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pcap} from '../models';
import {models} from '../models';

export function BatchDeleteFiles(arg1:Array<number>):Promise<void>;

export function DeleteFile(arg1:number):Promise<void>;

export function GetAllFrames(arg1:string):Promise<string>;

export function GetFileList(arg1:pcap.FileQueryReq):Promise<pcap.FileQueryResp>;

export function GetPacketDetail(arg1:string,arg2:number):Promise<string>;

export function GetPacketHex(arg1:string,arg2:number):Promise<string>;

export function GetPacketsByPage(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetWiresharkVersion():Promise<string>;

export function ImportFromPaths(arg1:Array<string>):Promise<Array<models.PcapFile>>;

export function ImportPcapsDialog():Promise<Array<models.PcapFile>>;
